add : プラグインの追加
SakuraProject/sakura-bot pull request #79
Opened 2022-10-23 05:24 UTC by ysmreg

2022-10-23 23:21 UTC, yaakiyu commented
まずちょっと
SakuraPluginについて説明できる?
僕は今のところあんまりどういう機能なのか分かってないから...

2022-10-23 23:28 UTC, ysmreg commented
> まずちょっと
> SakuraPluginについて説明できる?
> 僕は今のところあんまりどういう機能なのか分かってないから...

わかりました。SakuraPluginは非公開のプラグインを引き換えコードで導入したり公開プラグインを自由に導入してちょっとした機能追加をサーバーまたはユーザー用にできる機能です。非公開プラグインはsakurapointでコードと引き換えるかSakuraRPGのアイテムとして登場させることを考えています

2022-10-24 01:48 UTC, yaakiyu commented
sakuraRPGのアイテムにするのは反対(ゲームの中とか外の概念がぐちゃぐちゃになる。)
ちなみにSakuraPointをRPG内で使う時も「ショップ」にして、RPG内のコインと1日数量限定で交換するつもり。
あと、公開のプラグインってなんか意味とかメリットある?

2022-10-24 02:04 UTC, ysmreg commented
公開プラグインはメリットないです。ほとんど非公開のほうが良さそうです。非公開プラグインはショップまたはgiveawayなどのイベントで入手可能にしようかとおもいます

2022-10-24 04:09 UTC, yaakiyu commented
公開プラグインは「期間限定0Pointで入手可能」みたいにするか
とりあえずちょっと修正を要求
- ファイル名アンダーバー2つで始まるのはなるべくやめてほしい
- sakurabrandっていうカテゴリ作りたいから、新しくフォルダ作って欲しい。

2022-10-24 06:39 UTC, ysmreg commented
@yaakiyu 修整しました

2022-10-25 02:57 UTC, yaakiyu requested changes

2022-10-25 02:57 UTC, yaakiyu commented on main.py
> +        await bot.load_extension("cogs.sakurabrand.plugin")
この行いらない。
cogs/sakurabrand/\_\_init\_\_.pyで読み込まれる。

2022-10-25 02:57 UTC, yaakiyu commented on plugins/1/__init__.py
> +class music:
```suggestion
class Music:
```

2022-10-25 02:57 UTC, yaakiyu commented on plugins/1/__init__.py
> +        self.bot, self.before = bot, ""
```suggestion
        self.bot = bot
```

2022-10-25 02:57 UTC, yaakiyu commented on cogs/sakurabrand/plugin.py
> +def is_enable(func):
一応docstringを入れといて。
`Pluginが入っているかどうかを調べるデコレータです。`って

2022-10-25 02:57 UTC, yaakiyu commented on plugins/1/__init__.py
> +    await manager.add_class(music(bot, manager))
```suggestion
    await manager.add_class(Music(bot, manager))
```

2022-10-25 02:57 UTC, yaakiyu commented on plugins/2/__init__.py
> +from cogs.sakurabrand.plugin import PluginManager
そういえば、この`plugins`ってフォルダの中は、番号じゃなくてプラグイン名にして欲しいな。
そして、非公開プラグインは別のprivateリポジトリを作って、その中に入れてほしい。

2022-10-25 03:41 UTC, ysmreg commented on main.py
> +        await bot.load_extension("cogs.sakurabrand.plugin")
プラグインを一番最後に読み込まないと既存のclassを置き換え出来ないのでcogs.sakurabrand.__init__では読み込まれないようにしてあります

2022-10-25 03:43 UTC, ysmreg commented on plugins/2/__init__.py
> +from cogs.sakurabrand.plugin import PluginManager
Pluginsフォルダの中身をPublicとPrivateに分けて数字のフォルダはis_enableで登録されているidを取得するときに使っているのでidとタイトルを入れたフォルダ名に変えようとおもいます

2022-10-25 04:15 UTC, yaakiyu commented on main.py
> +        await bot.load_extension("cogs.sakurabrand.plugin")
[え？](https://github.com/SakuraProject/sakura-bot/blob/making-plugin/cogs/sakurabrand/__init__.py#L9)

2022-10-25 05:11 UTC, ysmreg commented on main.py
> +        await bot.load_extension("cogs.sakurabrand.plugin")
__init__.pyの7行目にnot name == "plugin.py"とあります

2022-10-25 05:16 UTC, yaakiyu commented on main.py
> +        await bot.load_extension("cogs.sakurabrand.plugin")
あ、なるほど
気がつかなかった

2022-10-25 07:18 UTC, ysmreg commented
@yaakiyu 変更しました

2022-10-26 01:24 UTC, yaakiyu commented
うーん
どうにかしてplugin用のhelp考えないとな

2022-10-27 04:36 UTC, yaakiyu approved these changes
Okay

2022-10-27 04:36 UTC, yaakiyu commented
プラグインのhelpは通常のhelpとは別に用意するか

2022-10-27 08:56 UTC, merged

2022-10-27 08:57 UTC, ysmreg commented
確かにプラグイン用のヘルプも必要かもです

2022-10-27 08:59 UTC, ysmreg commented
is_enableのデコレーターじゃないやつを作ってhelpのcogで有効になってるか確認して表示するかs_plugin helpというような別のコマンドで実装するかのどちらかが思いつきました