update: データ追加
SakuraProject/sakura-bot pull request #83
Opened 2022-10-27 01:45 UTC by yaakiyu

Helpなどのデータ関連の整備を行う。
* [x] cogsの型付け
* [ ] サブコマンドに対するhelpの構成を変更する
* [ ] helpデータ登録

2022-10-28 01:48 UTC, yaakiyu commented
あらなんかコマンドラインでmergeをしたら全部のコミット出てきちゃった
どうしよう()

2022-10-28 01:49 UTC, yaakiyu commented
ちょっと設定変えて、githubのUIでmergeできるようにした。
(このPRはスカッシュマージでもするか)

2022-10-28 02:43 UTC, yaakiyu commented
ちょっとpyrightの挙動修正したら大変なことになった

2022-10-31 04:36 UTC, yaakiyu commented
データ登録終了

2022-11-02 11:09 UTC, tuna2134 commented
Review終わったら呼んでね
あとactionsからOkayもらえるまでやってね

2022-11-03 08:56 UTC, yaakiyu commented
actionsからOkもらうのどんだけ大変だと思ってるんだよ()
(もともとyamlにおかしな引数入れてた誰かさんのせいだし...)
データ登録はやるから、そこらへんの修正は手伝ってくれ

2022-11-03 08:59 UTC, tuna2134 commented
> actionsからOkもらうのどんだけ大変だと思ってるんだよ()
> (もともとyamlにおかしな引数入れてた誰かさんのせいだし...)
> データ登録はやるから、そこらへんの修正は手伝ってくれ

えー、そもそも型とかpep8をしっかりやらんかった人だーれ？

2022-11-03 08:59 UTC, yaakiyu commented
(僕じゃ)ないです

2022-11-03 09:00 UTC, tuna2134 commented
> (僕じゃ)ないです

また書き直し第二弾やる？

2022-11-03 09:00 UTC, tuna2134 commented
これは本来の目的を達するだけでいいから

2022-11-03 09:03 UTC, tuna2134 commented
うぇこれ結構な量のやつやん
もうこのままやっちゃっていいよ()

2022-11-03 09:06 UTC, yaakiyu commented
んじゃもう本来の目的は達成済みなのでmerge

2022-11-03 09:07 UTC, merged

2022-11-03 09:11 UTC, tuna2134 requested changes
ちょっと修正依頼

2022-11-03 09:11 UTC, tuna2134 commented on cogs/bot/help.py
> +            [c for c in cog.create_categories_commands()[category_name] if " " not in c]
cの意味がわからんから意味持たせてくれ
省略やめて

2022-11-03 09:11 UTC, tuna2134 commented on cogs/entertainment/mynews.py
>          req = dict()
ついでに悪いんだが
reqに意味を持たせて欲しい
あと
req = {}にして

2022-11-03 09:11 UTC, tuna2134 commented on cogs/serverutil/globalchat.py
> -        self.channels_cache = []
型しっかり()

2022-11-03 09:12 UTC, tuna2134 commented
> んじゃもう本来の目的は達成済みなのでmerge

君さ？
まだreviewしてないんだよ()

2022-11-03 13:12 UTC, yaakiyu commented on cogs/entertainment/mynews.py
>          req = dict()
そこはまた別の機会にやる