[WIP]型付け及び型関連の修正
SakuraProject/sakura-bot pull request #85
Opened 2022-11-08 05:12 UTC by yaakiyu

Work In Progress...

2022-11-13 08:45 UTC, tuna2134 requested changes

2022-11-13 08:45 UTC, tuna2134 commented on cogs/automod/purge.py
>              mlis = list()
ついでなんだが
mlis = []にしてくれ()

2022-11-13 08:45 UTC, tuna2134 commented on cogs/entertainment/music.py
>          loop = asyncio.get_event_loop()
loopをbot.loopからとってきて

2022-11-13 08:45 UTC, tuna2134 commented on cogs/entertainment/reversi.py
> +        self.boards: dict = dict()
dict => {}

2022-11-13 08:45 UTC, tuna2134 commented on cogs/entertainment/reversi.py
> +        self.users: dict[int, str] = dict()
これも

2022-11-13 08:45 UTC, tuna2134 commented on cogs/entertainment/reversi.py
> +        self.upboard: dict = dict()
これも

2022-11-13 08:45 UTC, tuna2134 commented on cogs/entertainment/reversi.py
> +        math: dict[int | float, int] = dict()
dict => {}

2022-11-13 23:52 UTC, yaakiyu commented on cogs/automod/purge.py
>              mlis = list()
```suggestion
            mlis = []
```

2022-11-13 23:53 UTC, yaakiyu commented on cogs/entertainment/music.py
>          loop = asyncio.get_event_loop()
```suggestion
        loop = self.bot.loop
```

2022-11-13 23:53 UTC, yaakiyu commented on cogs/entertainment/reversi.py
> +        self.boards: dict = dict()
```suggestion
        self.boards: dict = {}
```

2022-11-14 00:35 UTC, tuna2134 approved these changes

2022-11-15 01:35 UTC, tuna2134 approved these changes

2022-11-16 05:16 UTC, tuna2134 approved these changes

2022-11-18 00:13 UTC, merged