カスタムprefix機能
SakuraProject/sakura-bot pull request #86
Opened 2022-11-09 05:40 UTC by yaakiyu

2022-11-09 08:30 UTC, tuna2134 requested changes
うえーい(?)

2022-11-09 08:30 UTC, tuna2134 commented on cogs/bot/prefix.py
> +    async def prepare_table(self, cursor: Cursor) -> tuple[
関数名変えて

2022-11-09 23:12 UTC, yaakiyu commented on cogs/bot/prefix.py
> +    async def prepare_table(self, cursor: Cursor) -> tuple[
何に変える?

2022-11-10 01:15 UTC, tuna2134 commented on cogs/bot/prefix.py
> +    async def prepare_table(self, cursor: Cursor) -> tuple[
setup_databaseとか

2022-11-10 01:46 UTC, yaakiyu commented on cogs/bot/prefix.py
> +    async def prepare_table(self, cursor: Cursor) -> tuple[
あんまり変わらない気がするんだが

2022-11-10 02:03 UTC, ysmreg commented on cogs/bot/prefix.py
> +    async def prepare_table(self, cursor: Cursor) -> tuple[
私もあまり変わらない気がします

2022-11-10 02:38 UTC, tuna2134 commented on cogs/bot/prefix.py
> +    async def prepare_table(self, cursor: Cursor) -> tuple[
prepare_tableはテーブルのセットアップ、そしてこのコードはテーブルとかテーブルのデータを引っ張ってセットしているから、あまりprepare_tableは使わん方がいい

2022-11-10 04:41 UTC, yaakiyu commented
なんかこのまま話しても不毛な議論になる気がしたので修正

2022-11-10 04:47 UTC, tuna2134 commented
> なんかこのまま話しても不毛な議論になる気がしたので修正

うーん、別名が思い付いたならそれにして
setup_prefixとか

2022-11-13 08:45 UTC, tuna2134 approved these changes

2022-11-13 23:51 UTC, merged